project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://ktruongme.github.io
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ktruongme
      - icon: rss
        href: index.xml
  page-footer:
    left: "© 2026 · Written in plain text, built with [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/ktruongme
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: [flatly, styles/base.scss, styles/light.scss]
      dark: [darkly, styles/base.scss, styles/dark.scss]
    highlight-style: a11y
    smooth-scroll: true
    link-external-newwindow: true
    respect-user-color-scheme: true



